language: ruby
rvm:
- 2.6
gemfile:
- gemfiles/jekyll_2.0.gemfile
- gemfiles/jekyll_3.0.gemfile
- gemfiles/jekyll_3.1.gemfile
- gemfiles/jekyll_3.8.gemfile
- gemfiles/jekyll_4.0.gemfile
script: bundle exec rspec
